### PR TITLE
Fixing issue 99

### PR DESCRIPTION
**Pull request by davidalain**
Fixes for issue #99

### CODE REVIEW

**Comment by sbondorf** [comment]
While at it, would you mind adding Javadocs to the method? We'd like to benefit from your expertise :-) Thanks!

**Comment by davidalain** [comment]
Hi @sbondorf.
I am checking what you have asked.
As soon as I have finished, I am going to answer and send a new pull request with javadocs.

**Comment by davidalain** [comment]
Hi @sbondorf .

Note1: The method `getXIntersection` does not break when it finds the **first** x-coordinate of the intersection of two segments. 
Then the resulting x-coordinate is the **last one** found among all that exist.
It is not the **smallest x intersection** when there are more than a **single** intersection, it is the **biggest x intersection**.
For instance, if one curve is concave and another is convex, we can have two intersections.
So what is the expected behavior of that method? Is it to find the **first** or the **last** x-coordinate among all intersections?

Note2: I think the method would not break at find two parallel segments as is done in lines 403-405.
For instance, if we have a curve1 (blue) composed of a single non-zero segment (i.e., an affine) and a curve2 (yellow) composed of more than two non-zero segments (i.e., piece-wise affine), then the single segment of curve1 can be parallel with one segment of curve2 but that single segment of curve1 can have an intersection with another segment of curve2.
image


Note3: Don't you prefer to check if input curves are wise-sense increasing and left-continuous?
I think I can write these verifications and include them in next commit.

**Comment by davidalain** [comment]
Hi @sbondorf.

After analyzing the method `getXIntersection()` more carefully, I could understand its behavior.

Thus, **Note1** I have wrote early does not apply.

What is your suggestion regarding **Note2** and **Note3**?

**Comment by sbondorf** [comment]
Thank you for the Javadocs and the inline comments, in particular Note 2 explaining lines 403-405 is very worthwhile to provide.

Having thought about Note 3 a bit more, I don't think we should work towards it at this part of the code. It is a more generic restriction on the input curves of the tool, yet, never explicitly checked. If somebody provided code checking for these properties, I'd thus move them to some class checking the network model before running any analysis.

**Pull request merged**
